### ISSUE TITLE
Lib Vlc Error 

### ISSUE THREAD

**Issue by zaanind** [zaanind/ZoomPlayer#1]
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod03_ctypes.py", line 53, in _init_
  File "ctypes\__init__.py", line 364, in _init_
OSError: [WinError 126] The specified module could not be found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "vlc.py", line 220, in <module>
  File "vlc.py", line 180, in find_lib
  File "PyInstaller\loader\pyimod03_ctypes.py", line 55, in _init_
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll '.\\libvlc.dll'. Most likely this dynlib/dll was not found when the application was frozen.

**Comment by zaanind** [comment]
Fixed, Download and install latest release again. the error should be fixed.
